# Generated by Django 3.2.6 on 2021-12-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeexpenseledgermodel',
            name='image',
        ),
        migrations.AddField(
            model_name='incomeexpenseledgermodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='incomeexpenseledgermodel',
            name='type',
            field=models.CharField(choices=[('', '----------'), ('income', 'Income'), ('expense', 'Expense'), ('cash-withdrawal', 'Cash Withdrawal'), ('cash-deposit', 'Cash Deposit')], max_length=100),
        ),
    ]
