# Generated by Django 3.2.6 on 2021-12-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20211216_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerfile',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Income expense ledger file'),
        ),
    ]
