# Generated by Django 3.2.6 on 2022-01-27 13:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_societymemberdetailsmodel_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societymemberdetailsmodel',
            name='primary_contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='societymemberdetailsmodel',
            name='secondary_contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='societymemberdetailsmodel',
            name='whatsapp_contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
